"""
Feature Configuration, Taxonomy Mappings, and Constants for CIC-IDS2017 NIDS.
"""

from typing import Dict, List, Set

# Full canonical feature list in the CIC-IDS2017 dataset (after whitespace strip)
# Total 78 numerical/statistical flow features + Label
RAW_NUMERIC_FEATURES: List[str] = [
    "Destination Port",
    "Flow Duration",
    "Total Fwd Packets",
    "Total Backward Packets",
    "Total Length of Fwd Packets",
    "Total Length of Bwd Packets",
    "Fwd Packet Length Max",
    "Fwd Packet Length Min",
    "Fwd Packet Length Mean",
    "Fwd Packet Length Std",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Flow IAT Min",
    "Fwd IAT Total",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Fwd IAT Max",
    "Fwd IAT Min",
    "Bwd IAT Total",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Bwd IAT Max",
    "Bwd IAT Min",
    "Fwd PSH Flags",
    "Bwd PSH Flags",
    "Fwd URG Flags",
    "Bwd URG Flags",
    "Fwd Header Length",
    "Bwd Header Length",
    "Fwd Packets/s",
    "Bwd Packets/s",
    "Min Packet Length",
    "Max Packet Length",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "FIN Flag Count",
    "SYN Flag Count",
    "RST Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "URG Flag Count",
    "CWE Flag Count",
    "ECE Flag Count",
    "Down/Up Ratio",
    "Average Packet Size",
    "Avg Fwd Segment Size",
    "Avg Bwd Segment Size",
    "Fwd Header Length.1",
    "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate",
    "Subflow Fwd Packets",
    "Subflow Fwd Bytes",
    "Subflow Bwd Packets",
    "Subflow Bwd Bytes",
    "Init_Win_bytes_forward",
    "Init_Win_bytes_backward",
    "act_data_pkt_fwd",
    "min_seg_size_forward",
    "Active Mean",
    "Active Std",
    "Active Max",
    "Active Min",
    "Idle Mean",
    "Idle Std",
    "Idle Max",
    "Idle Min",
]

# Columns in CIC-IDS2017 that typically have zero variance (constant zeros) across all days
ZERO_VARIANCE_CANDIDATES: Set[str] = {
    "Bwd PSH Flags",
    "Bwd URG Flags",
    "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate",
    "Fwd Header Length.1",  # duplicate of Fwd Header Length in CICFlowMeter
    "CWE Flag Count",
}

# High-impact feature subset optimized for real-time sub-millisecond inference
# Selected based on mutual information and Random Forest Gini impurity importance
TOP_SELECTED_FEATURES: List[str] = [
    "Destination Port",
    "Flow Duration",
    "Total Fwd Packets",
    "Total Backward Packets",
    "Total Length of Fwd Packets",
    "Total Length of Bwd Packets",
    "Fwd Packet Length Max",
    "Fwd Packet Length Min",
    "Fwd Packet Length Mean",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Fwd IAT Mean",
    "Bwd IAT Mean",
    "Fwd Header Length",
    "Bwd Header Length",
    "Fwd Packets/s",
    "Bwd Packets/s",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "SYN Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "URG Flag Count",
    "Average Packet Size",
    "Subflow Fwd Packets",
    "Subflow Fwd Bytes",
    "Subflow Bwd Packets",
    "Subflow Bwd Bytes",
    "Init_Win_bytes_forward",
    "Init_Win_bytes_backward",
    "act_data_pkt_fwd",
    "min_seg_size_forward",
    "Active Mean",
    "Idle Mean",
]

# Raw CIC-IDS2017 labels mapping to high-level Enterprise SOC categories
LABEL_TAXONOMY_MAP: Dict[str, str] = {
    "BENIGN": "BENIGN",
    "DDoS": "DDoS",
    "PortScan": "PortScan",
    "Bot": "Botnet",
    "Infiltration": "Infiltration",
    "Heartbleed": "DoS",
    "DoS Hulk": "DoS",
    "DoS GoldenEye": "DoS",
    "DoS slowloris": "DoS",
    "DoS Slowhttptest": "DoS",
    "FTP-Patator": "Brute Force",
    "SSH-Patator": "Brute Force",
    "Web Attack \x96 Brute Force": "Web Attack",
    "Web Attack – Brute Force": "Web Attack",
    "Web Attack - Brute Force": "Web Attack",
    "Web Attack \x96 XSS": "Web Attack",
    "Web Attack – XSS": "Web Attack",
    "Web Attack - XSS": "Web Attack",
    "Web Attack \x96 Sql Injection": "Web Attack",
    "Web Attack – Sql Injection": "Web Attack",
    "Web Attack - Sql Injection": "Web Attack",
}

# SOC Alert Metadata: Severity, MITRE ATT&CK Tactic, and Recommended Response
SOC_ALERT_METADATA: Dict[str, Dict[str, str]] = {
    "BENIGN": {
        "severity": "NORMAL",
        "color": "green",
        "tactic": "Normal Operations",
        "description": "Legitimate baseline network traffic.",
        "action": "Allow & Log",
    },
    "PortScan": {
        "severity": "SUSPICIOUS",
        "color": "amber",
        "tactic": "TA0043 - Reconnaissance",
        "description": "Sequential or SYN port scan attempting to discover open network services.",
        "action": "Rate-limit source IP & apply dynamic firewall drop rule.",
    },
    "Brute Force": {
        "severity": "HIGH",
        "color": "amber",
        "tactic": "TA0006 - Credential Access",
        "description": "Repeated authentication attempts against SSH or FTP services.",
        "action": "Enforce Fail2Ban, lock target account temporarily, verify MFA status.",
    },
    "Web Attack": {
        "severity": "HIGH",
        "color": "red",
        "tactic": "TA0001 - Initial Access",
        "description": "Exploit payloads targeting HTTP/HTTPS endpoints (SQLi, XSS, Path Traversal).",
        "action": "Trigger WAF block, inspect payload parameters, isolate impacted web pod.",
    },
    "Botnet": {
        "severity": "CRITICAL",
        "color": "red",
        "tactic": "TA0011 - Command and Control",
        "description": "Host exhibiting anomalous periodic beaconing patterns consistent with Ares botnet.",
        "action": "Quarantine endpoint from VLAN immediately, inspect active process tree.",
    },
    "DoS": {
        "severity": "CRITICAL",
        "color": "red",
        "tactic": "TA0040 - Impact",
        "description": "Volumetric or slow-rate Denial of Service attack exhausting server thread pools.",
        "action": "Enable aggressive TCP SYN cookies, scale backend instances, drop offending flow.",
    },
    "DDoS": {
        "severity": "CRITICAL",
        "color": "red",
        "tactic": "TA0040 - Impact",
        "description": "High-volume distributed flood saturating network bandwidth and gateway buffers.",
        "action": "Activate upstream scrub center, divert traffic to BGP Anycast null route.",
    },
    "Infiltration": {
        "severity": "CRITICAL",
        "color": "red",
        "tactic": "TA0008 - Lateral Movement",
        "description": "Post-exploitation lateral movement attempt utilizing compromised internal host.",
        "action": "Sever east-west microsegmentation tunnels, initiate DFIR incident response.",
    },
}
